# Generated by Django 6.0.2 on 2026-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grain', 'Grains/Cereals'), ('Vegetable', 'Vegetables'), ('Fruit', 'Fruits'), ('Spices', 'Spices')], default='Grain', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='crop_image',
            field=models.ImageField(upload_to='market_products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Price in ₹', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(help_text='e.g., 500 KG or 10 Quintals', max_length=100),
        ),
    ]
