# Generated by Django 6.0.2 on 2026-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='crop_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
