# Generated by Django 6.0.2 on 2026-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0008_rename_crop_image_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
