# Generated by Django 6.0.2 on 2026-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0010_equipment_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default=0, help_text='e.g., Tractor, Harvester, Drone', max_length=100),
            preserve_default=False,
        ),
    ]
