# Generated by Django 6.0.2 on 2026-02-25 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0013_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdate',
            name='category',
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
