# Generated by Django 6.0.2 on 2026-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0014_remove_newsupdate_category_newsupdate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
